spring.application.name=retailflow-saas-pos
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5433/retailflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
app.jwt.secret=retailflow-super-secret-key-for-development-only-please-change
app.jwt.expiration-ms=86400000
